version: "3"

services:
    nominatim:
        container_name: nominatim
        image: mediagis/nominatim:4.5
        ports:
            - "8080:8080"
        environment:
            # see https://github.com/mediagis/nominatim-docker/tree/master/4.5#configuration for more options
            PBF_URL: http://download.geofabrik.de/north-america/us-midwest-latest.osm.pbf
            REPLICATION_URL: http://download.geofabrik.de/north-america/us-midwest-updates/
            NOMINATIM_PASSWORD: very_secure_password
            IMPORT_TIGER_ADDRESSES: true
            IMPORT_US_POSTCODES: true
        volumes:
            - nominatim-data:/var/lib/postgresql/16/main
        shm_size: 1gb

volumes:
    nominatim-data: